### ISSUE TITLE
Per convenzione i metodi async devono avere il suffisso "Async"

### ISSUE THREAD

**Issue by pietroserrano** [memoryleak07/Safemoney_UnitTest1_NET8#1]
https://github.com/memoryleak07/Safemoney_UnitTest1_NET8/blob/e6103dea6bd3f3b020136c38853ffba5c2c75a6b/Safemoney_UnitTest1_NET8/Classes/ResponseManager.cs#L15

**Comment by memoryleak07** [comment]
Ok, eliminata "ManageBadResponse()" gestisco tutto nella funz. rinominata  "ReadResponseAsync()" della classe ResponseManager.
