### ISSUE TITLE
Utilizzare direttamente HttpClient

### ISSUE THREAD

**Issue by pietroserrano** [memoryleak07/Safemoney_UnitTest1_NET8#2]
Potresti utilizzare direttamente l'HttpClient qui, senza passare per quel wrap che porta solo un ulteriore wrap.
Il metodo per fare la build della request, se necessario, potresti farlo diventare un metodo di una classe statica (che potresti chiamare HttpUtility) cosi da richiamarlo dove ti serve.

https://github.com/memoryleak07/Safemoney_UnitTest1_NET8/blob/e6103dea6bd3f3b020136c38853ffba5c2c75a6b/Safemoney_UnitTest1_NET8/Classes/RestClient.cs#L16

**Comment by memoryleak07** [comment]
1) Eliminata classe HTTPClient: ora RestClient fornisce accesso ai methodi built-in di HttpClient e include una instanza di una nuova classe (HttpRequestManager) per gestire le chiamate persoanlizzate (Paga, Spegni, etc):

Es:
            //built-in
            var res = await client.HttpClient.GetAsync("get");
           // custom
            var res = await client.RequestManager.Pay(payload);

Per ora ho fatto 4 overload per RestClient. (url, port, etc.)

2) Aggiunta una classe HttpUtility per:
- Fare il build della url 
- Aggiungere basic auth all' headers
- Costruire un HttpRequestMessage da un oggetto 

*** Le modifiche stanno in "branch1" ***
